"""empty message

Revision ID: 01806928b317
Revises: a9b5e7e9b937
Create Date: 2025-12-03 05:06:41.792245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01806928b317'
down_revision = 'a9b5e7e9b937'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('People',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('birth_year', sa.String(length=25), nullable=False),
    sa.Column('creacted', sa.String(length=100), nullable=False),
    sa.Column('eye_color', sa.String(length=10), nullable=False),
    sa.Column('Films', sa.String(length=500), nullable=False),
    sa.Column('gender', sa.String(length=15), nullable=False),
    sa.Column('heir_color', sa.String(length=25), nullable=False),
    sa.Column('height', sa.String(length=25), nullable=False),
    sa.Column('homeworld', sa.String(length=250), nullable=False),
    sa.Column('skin_color', sa.String(length=25), nullable=False),
    sa.Column('species', sa.String(length=300), nullable=False),
    sa.Column('starships', sa.String(length=500), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('Films'),
    sa.UniqueConstraint('birth_year'),
    sa.UniqueConstraint('creacted'),
    sa.UniqueConstraint('eye_color'),
    sa.UniqueConstraint('gender'),
    sa.UniqueConstraint('height'),
    sa.UniqueConstraint('heir_color'),
    sa.UniqueConstraint('homeworld'),
    sa.UniqueConstraint('skin_color'),
    sa.UniqueConstraint('species'),
    sa.UniqueConstraint('starships'),
    sa.UniqueConstraint('url')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('People')
    # ### end Alembic commands ###
