"""empty message

Revision ID: 6d9a153c998c
Revises: 9d0bd8ac2f86
Create Date: 2025-12-03 05:39:48.004913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d9a153c998c'
down_revision = '9d0bd8ac2f86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Starship',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('Films', sa.String(length=500), nullable=False),
    sa.Column('MGLT', sa.String(length=25), nullable=False),
    sa.Column('cargo_capacity', sa.String(length=50), nullable=False),
    sa.Column('consumable', sa.String(length=10), nullable=False),
    sa.Column('coult_in_credits', sa.String(length=50), nullable=False),
    sa.Column('created', sa.String(length=75), nullable=False),
    sa.Column('crew', sa.String(length=25), nullable=False),
    sa.Column('homeworld', sa.String(length=250), nullable=False),
    sa.Column('starships_type', sa.String(length=500), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('Films'),
    sa.UniqueConstraint('MGLT'),
    sa.UniqueConstraint('cargo_capacity'),
    sa.UniqueConstraint('consumable'),
    sa.UniqueConstraint('coult_in_credits'),
    sa.UniqueConstraint('created'),
    sa.UniqueConstraint('crew'),
    sa.UniqueConstraint('homeworld'),
    sa.UniqueConstraint('starships_type'),
    sa.UniqueConstraint('url')
    )
    with op.batch_alter_table('Favotite', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'Starship', ['starships_id'], ['ID'])

    with op.batch_alter_table('Films', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'Starship', ['starships_id'], ['ID'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Films', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('Favotite', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    op.drop_table('Starship')
    # ### end Alembic commands ###
