"""empty message

Revision ID: a9b5e7e9b937
Revises: d67c54521238
Create Date: 2025-12-02 09:56:24.805355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9b5e7e9b937'
down_revision = 'd67c54521238'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Films',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('charatecrs', sa.String(length=300), nullable=False),
    sa.Column('creacted', sa.String(length=75), nullable=False),
    sa.Column('director', sa.String(length=75), nullable=False),
    sa.Column('episode', sa.String(length=10), nullable=False),
    sa.Column('opening_crawl', sa.String(length=30), nullable=False),
    sa.Column('people_id', sa.Integer(), nullable=False),
    sa.Column('planets', sa.String(length=300), nullable=False),
    sa.Column('planets_id', sa.Integer(), nullable=False),
    sa.Column('producer', sa.String(length=10), nullable=False),
    sa.Column('release_date', sa.String(length=30), nullable=False),
    sa.Column('species', sa.String(length=300), nullable=False),
    sa.Column('species_id', sa.Integer(), nullable=False),
    sa.Column('starships', sa.String(length=300), nullable=False),
    sa.Column('starships_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('charatecrs'),
    sa.UniqueConstraint('creacted'),
    sa.UniqueConstraint('director'),
    sa.UniqueConstraint('episode'),
    sa.UniqueConstraint('opening_crawl'),
    sa.UniqueConstraint('planets'),
    sa.UniqueConstraint('producer'),
    sa.UniqueConstraint('release_date'),
    sa.UniqueConstraint('species'),
    sa.UniqueConstraint('starships'),
    sa.UniqueConstraint('title')
    )
    with op.batch_alter_table('Favotite', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'Films', ['films_id'], ['ID'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Favotite', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    op.drop_table('Films')
    # ### end Alembic commands ###
