"""empty message

Revision ID: ccec2f9256b1
Revises: 6d9a153c998c
Create Date: 2025-12-03 06:01:41.629684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccec2f9256b1'
down_revision = '6d9a153c998c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Planet',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('films', sa.String(length=500), nullable=False),
    sa.Column('resource', sa.String(length=300), nullable=False),
    sa.Column('poblation', sa.String(length=50), nullable=False),
    sa.Column('consumable', sa.String(length=10), nullable=False),
    sa.Column('coult_in_credits', sa.String(length=50), nullable=False),
    sa.Column('height', sa.String(length=75), nullable=False),
    sa.Column('homeworld', sa.String(length=250), nullable=False),
    sa.Column('climatic_conditions', sa.String(length=500), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('climatic_conditions'),
    sa.UniqueConstraint('consumable'),
    sa.UniqueConstraint('coult_in_credits'),
    sa.UniqueConstraint('films'),
    sa.UniqueConstraint('height'),
    sa.UniqueConstraint('homeworld'),
    sa.UniqueConstraint('poblation'),
    sa.UniqueConstraint('resource'),
    sa.UniqueConstraint('url')
    )
    with op.batch_alter_table('Favotite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planets_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'Planet', ['planets_id'], ['ID'])

    with op.batch_alter_table('Films', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'Planet', ['planets_id'], ['ID'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Films', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('Favotite', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('planets_id')

    op.drop_table('Planet')
    # ### end Alembic commands ###
